name: CODEARTIFACT
description: Login code artifact
author: tbd
requirements:
  - bash
  - aws
configuration:
  properties:
    account-id:
      type:
        - string
    region:
      type: string
    username:
      type: string
    domain:
      type: string
    repository:
      type: string
