#!/bin/bash
set -euo pipefail

function plugin_read_list() {
  local prefix="BUILDKITE_PLUGIN_CODE_ARTIFACT_$1"
  local parameter="${prefix}_0"

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      echo "${!parameter}"
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    echo "${!prefix}"
  fi
}

function get_vars_prefix() {
    local prefix="$BUILDKITE_PLUGIN_CODE_ARTIFACT_PREFIX"

    if [[ -n "prefix" ]]; then
      echo "${prefix}_"
    else
      echo ""
    fi
}

function install_aws(){
  curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip 2>/dev/null
  unzip -qq awscli-bundle.zip
  ./awscli-bundle/install -b ~/bin/aws
}

function login(){
  local id="$1"
  local region="$BUILDKITE_PLUGIN_CODE_ARTIFACT_REGION"
  local domain="$BUILDKITE_PLUGIN_CODE_ARTIFACT_DOMAIN"
  local path="$BUILDKITE_PLUGIN_CODE_ARTIFACT_PATH"
  local username="$BUILDKITE_PLUGIN_CODE_ARTIFACT_USERNAME"

  export TWINE_REPOSITORY_URL=$(aws codeartifact get-repository-endpoint --region "${region}" --domain="${domain}" --domain-owner="${id}" --repository="${domain}" --format pypi --query repositoryEndpoint --output text)
  export TWINE_PASSWORD=$(aws codeartifact get-authorization-token --region "${region}" --domain="${domain}" --domain-owner="${id}" --query authorizationToken --output text)
  export TWINE_USERNAME="${username}"
  export PIP_INDEX_URL="https://aws:${TWINE_PASSWORD}@${domain}-${id}.d.codeartifact.${region}.amazonaws.com/pypi/${domain}/${path}"

  echo "{\"key\":\"${TWINE_REPOSITORY_URL}\",\"key\":\"${TWINE_PASSWORD}\",\"key\":\"${TWINE_USERNAME}\",\"key\":\"${PIP_INDEX_URL}\"}" | buildkite-agent redactor add --format json
}

function login_code_artifact(){
  registry_ids=()
  while IFS='' read -r line; do registry_ids+=("$line"); done < <(plugin_read_list ACCOUNT_IDS | tr "," "\n")
  for id in "${registry_ids[@]}"
  do
    login "$id"
  done;
  echo "Hello world from buildkite hook plugin"
}

login_code_artifact