#!/bin/bash
set -euo pipefail

set -x

env | sort

# Logs in to AWS CodeArtifact and sets up authentication for Twine and Pip
function login_code_artifact() {
  local account_id="${BUILDKITE_PLUGIN_CODE_ARTIFACT_ACCOUNT_ID}"
  local region="${BUILDKITE_PLUGIN_CODE_ARTIFACT_REGION}"
  local domain="${BUILDKITE_PLUGIN_CODE_ARTIFACT_DOMAIN}"
  local repository="${BUILDKITE_PLUGIN_CODE_ARTIFACT_REPOSITORY}"

  export TWINE_USERNAME="aws"
  export TWINE_PASSWORD=$(aws codeartifact get-authorization-token --region "${region}" --domain="${domain}" --domain-owner="${account_id}" --query authorizationToken --output text)
  echo "$TWINE_PASSWORD" | buildkite-agent redactor add
  export TWINE_REPOSITORY_URL=$(aws codeartifact get-repository-endpoint --region "${region}" --domain="${domain}" --domain-owner="${account_id}" --repository="${repository}" --format pypi --query repositoryEndpoint --output text)
  export PIP_INDEX_URL="https://${TWINE_USERNAME}:${TWINE_PASSWORD}@${domain}-${account_id}.d.codeartifact.${region}.amazonaws.com/pypi/${domain}/simple"
}

login_code_artifact
